2023-11-25 08:46:38.974 UTC [2337547] LOG:  number of prepared transactions has not been configured, overriding
2023-11-25 08:46:38.974 UTC [2337547] DETAIL:  max_prepared_transactions is now set to 200
2023-11-25 08:46:38.991 UTC [2337547] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-11-25 08:46:38.992 UTC [2337547] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-11-25 08:46:38.997 UTC [2337547] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-11-25 08:46:39.008 UTC [2337550] LOG:  database system was shut down at 2023-11-25 08:46:38 UTC
2023-11-25 08:46:39.015 UTC [2337547] LOG:  database system is ready to accept connections
2023-11-25 08:46:39.382 UTC [2337570] LOG:  starting maintenance daemon on database 16384 user 10
2023-11-25 08:46:39.382 UTC [2337570] CONTEXT:  Citus maintenance daemon for database 16384 user 10
2023-11-25 08:46:39.412 UTC [2337569] ERROR:  not a Python mapping
2023-11-25 08:46:39.412 UTC [2337569] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-11-25 08:46:39.412 UTC [2337569] STATEMENT:  SELECT test1bad();
2023-11-25 08:46:39.422 UTC [2337569] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-11-25 08:46:39.422 UTC [2337569] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-11-25 08:46:39.422 UTC [2337569] STATEMENT:  SELECT test2dom('bar');
