2023-07-26 04:49:06.166 UTC [3400879] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-26 04:49:06.166 UTC [3400879] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-26 04:49:06.179 UTC [3400879] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-26 04:49:06.195 UTC [3400882] LOG:  database system was shut down at 2023-07-26 04:49:05 UTC
2023-07-26 04:49:06.204 UTC [3400879] LOG:  database system is ready to accept connections
2023-07-26 04:49:06.614 UTC [3400901] ERROR:  parameter "extensions" must be a list of extension names
2023-07-26 04:49:06.614 UTC [3400901] STATEMENT:  ALTER SERVER testserver1 OPTIONS (ADD extensions 'foo; bar');
2023-07-26 04:49:06.615 UTC [3400901] WARNING:  extension "foo" is not installed
2023-07-26 04:49:06.615 UTC [3400901] WARNING:  extension "bar" is not installed
2023-07-26 04:49:06.624 UTC [3400901] ERROR:  invalid option "sslmode"
2023-07-26 04:49:06.624 UTC [3400901] HINT:  Valid options in this context are: user, password, sslpassword, password_required, sslcert, sslkey
2023-07-26 04:49:06.624 UTC [3400901] STATEMENT:  ALTER USER MAPPING FOR public SERVER testserver1
		OPTIONS (ADD sslmode 'require');
2023-07-26 04:49:06.682 UTC [3400903] FATAL:  database "no such database" does not exist
2023-07-26 04:49:06.682 UTC [3400901] ERROR:  could not connect to server "loopback"
2023-07-26 04:49:06.682 UTC [3400901] DETAIL:  connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "no such database" does not exist
2023-07-26 04:49:06.682 UTC [3400901] STATEMENT:  SELECT c3, c4 FROM ft1 ORDER BY c3, c1 LIMIT 1;
2023-07-26 04:49:06.710 UTC [3400905] FATAL:  role "no such user" does not exist
2023-07-26 04:49:06.710 UTC [3400901] ERROR:  could not connect to server "loopback"
2023-07-26 04:49:06.710 UTC [3400901] DETAIL:  connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  role "no such user" does not exist
2023-07-26 04:49:06.710 UTC [3400901] STATEMENT:  SELECT c3, c4 FROM ft1 ORDER BY c3, c1 LIMIT 1;
2023-07-26 04:49:06.746 UTC [3400901] ERROR:  cannot add relation "ft1" to publication
2023-07-26 04:49:06.746 UTC [3400901] DETAIL:  This operation is not supported for foreign tables.
2023-07-26 04:49:06.746 UTC [3400901] STATEMENT:  CREATE PUBLICATION testpub_ftbl FOR TABLE ft1;
2023-07-26 04:49:07.090 UTC [3400901] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:07.090 UTC [3400901] STATEMENT:  EXPLAIN (VERBOSE, COSTS OFF)
	SELECT c1,c2,c3 FROM ft2 WHERE CASE CASE WHEN c2 > 0 THEN c2 END WHEN 100 THEN 601 WHEN c2 THEN c2 ELSE 0 END > 600 ORDER BY c1;
2023-07-26 04:49:07.090 UTC [3400901] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:07.090 UTC [3400901] STATEMENT:  SELECT c1,c2,c3 FROM ft2 WHERE CASE CASE WHEN c2 > 0 THEN c2 END WHEN 100 THEN 601 WHEN c2 THEN c2 ELSE 0 END > 600 ORDER BY c1;
2023-07-26 04:49:07.091 UTC [3400901] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:07.091 UTC [3400901] STATEMENT:  EXPLAIN (VERBOSE, COSTS OFF)
	SELECT * FROM ft1 WHERE c1 > (CASE mod(c1, 4) WHEN 0 THEN 1 WHEN 2 THEN 50 ELSE 100 END);
2023-07-26 04:49:07.092 UTC [3400901] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:07.092 UTC [3400901] STATEMENT:  EXPLAIN (VERBOSE, COSTS OFF)
	SELECT * FROM ft1 WHERE c1 > (CASE random()::integer WHEN 0 THEN 1 WHEN 2 THEN 50 ELSE 100 END);
2023-07-26 04:49:07.092 UTC [3400901] ERROR:  cache lookup failed for type 1043
2023-07-26 04:49:07.092 UTC [3400901] STATEMENT:  EXPLAIN (VERBOSE, COSTS OFF)
	SELECT * FROM ft1 WHERE CASE c6 WHEN 'foo' THEN true ELSE c3 < 'bar' END;
2023-07-26 04:49:07.093 UTC [3400901] ERROR:  cache lookup failed for type 25
2023-07-26 04:49:07.093 UTC [3400901] STATEMENT:  EXPLAIN (VERBOSE, COSTS OFF)
	SELECT * FROM ft1 WHERE CASE c3 WHEN c6 THEN true ELSE c3 < 'bar' END;
2023-07-26 04:49:07.094 UTC [3400901] ERROR:  cache lookup failed for type 25
2023-07-26 04:49:07.094 UTC [3400901] STATEMENT:  EXPLAIN (VERBOSE, COSTS OFF)
	SELECT * FROM ft1 WHERE CASE c3 COLLATE "C" WHEN c6 THEN true ELSE c3 < 'bar' END;
2023-07-26 04:49:08.394 UTC [3400901] ERROR:  "reindex_foreign" is not a table or materialized view
2023-07-26 04:49:08.394 UTC [3400901] STATEMENT:  REINDEX TABLE reindex_foreign;
2023-07-26 04:49:08.394 UTC [3400901] ERROR:  "reindex_foreign" is not a table or materialized view
2023-07-26 04:49:08.394 UTC [3400901] STATEMENT:  REINDEX TABLE CONCURRENTLY reindex_foreign;
2023-07-26 04:49:08.414 UTC [3400901] ERROR:  invalid input syntax for type integer: "foo"
2023-07-26 04:49:08.414 UTC [3400901] CONTEXT:  column "x8" of foreign table "ftx"
2023-07-26 04:49:08.414 UTC [3400901] STATEMENT:  SELECT * FROM ft1 ftx(x1,x2,x3,x4,x5,x6,x7,x8) WHERE x1 = 1;
2023-07-26 04:49:08.415 UTC [3400901] ERROR:  invalid input syntax for type integer: "foo"
2023-07-26 04:49:08.415 UTC [3400901] CONTEXT:  column "x8" of foreign table "ftx"
2023-07-26 04:49:08.415 UTC [3400901] STATEMENT:  SELECT ftx.x1, ft2.c2, ftx.x8 FROM ft1 ftx(x1,x2,x3,x4,x5,x6,x7,x8), ft2
	  WHERE ftx.x1 = ft2.c1 AND ftx.x1 = 1;
2023-07-26 04:49:08.416 UTC [3400901] ERROR:  invalid input syntax for type integer: "foo"
2023-07-26 04:49:08.416 UTC [3400901] CONTEXT:  whole-row reference to foreign table "ftx"
2023-07-26 04:49:08.416 UTC [3400901] STATEMENT:  SELECT ftx.x1, ft2.c2, ftx FROM ft1 ftx(x1,x2,x3,x4,x5,x6,x7,x8), ft2
	  WHERE ftx.x1 = ft2.c1 AND ftx.x1 = 1;
2023-07-26 04:49:08.417 UTC [3400901] ERROR:  invalid input syntax for type integer: "foo"
2023-07-26 04:49:08.417 UTC [3400901] CONTEXT:  processing expression at position 2 in select list
2023-07-26 04:49:08.417 UTC [3400901] STATEMENT:  SELECT sum(c2), array_agg(c8) FROM ft1 GROUP BY c8;
2023-07-26 04:49:08.418 UTC [3400901] ERROR:  invalid input syntax for type integer: "foo"
2023-07-26 04:49:08.418 UTC [3400901] CONTEXT:  column "c8" of foreign table "ft1"
2023-07-26 04:49:08.418 UTC [3400901] STATEMENT:  ANALYZE ft1;
2023-07-26 04:49:08.433 UTC [3400919] ERROR:  operator does not exist: public.user_enum ~~ unknown at character 92
2023-07-26 04:49:08.433 UTC [3400919] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
2023-07-26 04:49:08.433 UTC [3400919] STATEMENT:  DECLARE c1 CURSOR FOR
	SELECT "C 1", c2, c3, c4, c5, c6, c7, c8 FROM "S 1"."T 1" WHERE ((c8 ~~ 'foo')) LIMIT 1::bigint
2023-07-26 04:49:08.433 UTC [3400901] ERROR:  operator does not exist: public.user_enum ~~ unknown
2023-07-26 04:49:08.433 UTC [3400901] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
2023-07-26 04:49:08.433 UTC [3400901] CONTEXT:  remote SQL command: SELECT "C 1", c2, c3, c4, c5, c6, c7, c8 FROM "S 1"."T 1" WHERE ((c8 ~~ 'foo')) LIMIT 1::bigint
2023-07-26 04:49:08.433 UTC [3400901] STATEMENT:  SELECT * FROM ft1 WHERE c8 LIKE 'foo' LIMIT 1;
2023-07-26 04:49:08.434 UTC [3400919] ERROR:  operator does not exist: public.user_enum ~~ unknown at character 92
2023-07-26 04:49:08.434 UTC [3400919] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
2023-07-26 04:49:08.434 UTC [3400919] STATEMENT:  DECLARE c1 CURSOR FOR
	SELECT "C 1", c2, c3, c4, c5, c6, c7, c8 FROM "S 1"."T 1" WHERE ((c8 ~~ 'foo')) LIMIT 1::bigint
2023-07-26 04:49:08.435 UTC [3400901] ERROR:  operator does not exist: public.user_enum ~~ unknown
2023-07-26 04:49:08.435 UTC [3400901] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
2023-07-26 04:49:08.435 UTC [3400901] CONTEXT:  remote SQL command: SELECT "C 1", c2, c3, c4, c5, c6, c7, c8 FROM "S 1"."T 1" WHERE ((c8 ~~ 'foo')) LIMIT 1::bigint
2023-07-26 04:49:08.435 UTC [3400901] STATEMENT:  SELECT * FROM ft1 WHERE c8::text LIKE 'foo' LIMIT 1;
2023-07-26 04:49:08.441 UTC [3400901] ERROR:  syntax error at or near "ERROR" at character 1
2023-07-26 04:49:08.441 UTC [3400901] STATEMENT:  ERROR OUT;
2023-07-26 04:49:08.444 UTC [3400919] ERROR:  division by zero
2023-07-26 04:49:08.444 UTC [3400919] STATEMENT:  FETCH 100 FROM c2
2023-07-26 04:49:08.445 UTC [3400901] ERROR:  division by zero
2023-07-26 04:49:08.445 UTC [3400901] CONTEXT:  remote SQL command: SELECT "C 1", c2, c3, c4, c5, c6, c7, c8 FROM "S 1"."T 1" WHERE (((1 / ("C 1" - 1)) > 0))
2023-07-26 04:49:08.445 UTC [3400901] STATEMENT:  SELECT * FROM ft1 WHERE 1 / (c1 - 1) > 0;
2023-07-26 04:49:08.561 UTC [3400901] ERROR:  cache lookup failed for type 1042
2023-07-26 04:49:08.561 UTC [3400901] STATEMENT:  EXPLAIN (verbose, costs off)
	UPDATE ft2 SET c2 = ft2.c2 + 500, c3 = ft2.c3 || '_update9', c7 = DEFAULT
	  FROM ft1 WHERE ft1.c1 = ft2.c2 AND ft1.c1 % 10 = 9;
2023-07-26 04:49:08.562 UTC [3400901] ERROR:  cache lookup failed for type 1042
2023-07-26 04:49:08.562 UTC [3400901] STATEMENT:  UPDATE ft2 SET c2 = ft2.c2 + 500, c3 = ft2.c3 || '_update9', c7 = DEFAULT
	  FROM ft1 WHERE ft1.c1 = ft2.c2 AND ft1.c1 % 10 = 9;
2023-07-26 04:49:08.930 UTC [3400921] ERROR:  duplicate key value violates unique constraint "t1_pkey"
2023-07-26 04:49:08.930 UTC [3400921] DETAIL:  Key ("C 1")=(11) already exists.
2023-07-26 04:49:08.930 UTC [3400921] STATEMENT:  INSERT INTO "S 1"."T 1"("C 1", c2, c3, c4, c5, c6, c7, c8) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2023-07-26 04:49:08.930 UTC [3400901] ERROR:  duplicate key value violates unique constraint "t1_pkey"
2023-07-26 04:49:08.930 UTC [3400901] DETAIL:  Key ("C 1")=(11) already exists.
2023-07-26 04:49:08.930 UTC [3400901] CONTEXT:  remote SQL command: INSERT INTO "S 1"."T 1"("C 1", c2, c3, c4, c5, c6, c7, c8) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2023-07-26 04:49:08.930 UTC [3400901] STATEMENT:  INSERT INTO ft1(c1, c2) VALUES(11, 12);
2023-07-26 04:49:08.934 UTC [3400901] ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
2023-07-26 04:49:08.934 UTC [3400901] STATEMENT:  INSERT INTO ft1(c1, c2) VALUES(11, 12) ON CONFLICT (c1, c2) DO NOTHING;
2023-07-26 04:49:08.934 UTC [3400901] ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
2023-07-26 04:49:08.934 UTC [3400901] STATEMENT:  INSERT INTO ft1(c1, c2) VALUES(11, 12) ON CONFLICT (c1, c2) DO UPDATE SET c3 = 'ffg';
2023-07-26 04:49:08.936 UTC [3400921] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:08.936 UTC [3400921] DETAIL:  Failing row contains (1111, -2, null, null, null, null, ft1       , null).
2023-07-26 04:49:08.936 UTC [3400921] STATEMENT:  INSERT INTO "S 1"."T 1"("C 1", c2, c3, c4, c5, c6, c7, c8) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2023-07-26 04:49:08.936 UTC [3400901] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:08.936 UTC [3400901] DETAIL:  Failing row contains (1111, -2, null, null, null, null, ft1       , null).
2023-07-26 04:49:08.936 UTC [3400901] CONTEXT:  remote SQL command: INSERT INTO "S 1"."T 1"("C 1", c2, c3, c4, c5, c6, c7, c8) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2023-07-26 04:49:08.936 UTC [3400901] STATEMENT:  INSERT INTO ft1(c1, c2) VALUES(1111, -2);
2023-07-26 04:49:08.938 UTC [3400921] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:08.938 UTC [3400921] DETAIL:  Failing row contains (1, -1, 00001_trig_update, 1970-01-02 08:00:00+00, 1970-01-02 00:00:00, 1, 1         , foo).
2023-07-26 04:49:08.938 UTC [3400921] STATEMENT:  UPDATE "S 1"."T 1" SET c2 = (- c2) WHERE (("C 1" = 1))
2023-07-26 04:49:08.938 UTC [3400901] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:08.938 UTC [3400901] DETAIL:  Failing row contains (1, -1, 00001_trig_update, 1970-01-02 08:00:00+00, 1970-01-02 00:00:00, 1, 1         , foo).
2023-07-26 04:49:08.938 UTC [3400901] CONTEXT:  remote SQL command: UPDATE "S 1"."T 1" SET c2 = (- c2) WHERE (("C 1" = 1))
2023-07-26 04:49:08.938 UTC [3400901] STATEMENT:  UPDATE ft1 SET c2 = -c2 WHERE c1 = 1;
2023-07-26 04:49:08.997 UTC [3400921] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:08.997 UTC [3400921] DETAIL:  Failing row contains (10, -2, 00010_trig_update_trig_update, 1970-01-11 08:00:00+00, 1970-01-11 00:00:00, 0, 0         , foo).
2023-07-26 04:49:08.997 UTC [3400921] STATEMENT:  UPDATE "S 1"."T 1" SET c2 = (-2) WHERE ((c2 = 42)) AND (("C 1" = 10))
2023-07-26 04:49:08.997 UTC [3400901] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:08.997 UTC [3400901] DETAIL:  Failing row contains (10, -2, 00010_trig_update_trig_update, 1970-01-11 08:00:00+00, 1970-01-11 00:00:00, 0, 0         , foo).
2023-07-26 04:49:08.997 UTC [3400901] CONTEXT:  remote SQL command: UPDATE "S 1"."T 1" SET c2 = (-2) WHERE ((c2 = 42)) AND (("C 1" = 10))
2023-07-26 04:49:08.997 UTC [3400901] STATEMENT:  update ft2 set c2 = -2 where c2 = 42 and c1 = 10;
2023-07-26 04:49:09.069 UTC [3400921] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:09.069 UTC [3400921] DETAIL:  Failing row contains (1111, -2, null, null, null, null, ft1       , null).
2023-07-26 04:49:09.069 UTC [3400921] STATEMENT:  INSERT INTO "S 1"."T 1"("C 1", c2, c3, c4, c5, c6, c7, c8) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2023-07-26 04:49:09.069 UTC [3400901] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:09.069 UTC [3400901] DETAIL:  Failing row contains (1111, -2, null, null, null, null, ft1       , null).
2023-07-26 04:49:09.069 UTC [3400901] CONTEXT:  remote SQL command: INSERT INTO "S 1"."T 1"("C 1", c2, c3, c4, c5, c6, c7, c8) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2023-07-26 04:49:09.069 UTC [3400901] STATEMENT:  INSERT INTO ft1(c1, c2) VALUES(1111, -2);
2023-07-26 04:49:09.071 UTC [3400921] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:09.071 UTC [3400921] DETAIL:  Failing row contains (1, -1, 00001_trig_update, 1970-01-02 08:00:00+00, 1970-01-02 00:00:00, 1, 1         , foo).
2023-07-26 04:49:09.071 UTC [3400921] STATEMENT:  UPDATE "S 1"."T 1" SET c2 = (- c2) WHERE (("C 1" = 1))
2023-07-26 04:49:09.071 UTC [3400901] ERROR:  new row for relation "T 1" violates check constraint "c2positive"
2023-07-26 04:49:09.071 UTC [3400901] DETAIL:  Failing row contains (1, -1, 00001_trig_update, 1970-01-02 08:00:00+00, 1970-01-02 00:00:00, 1, 1         , foo).
2023-07-26 04:49:09.071 UTC [3400901] CONTEXT:  remote SQL command: UPDATE "S 1"."T 1" SET c2 = (- c2) WHERE (("C 1" = 1))
2023-07-26 04:49:09.071 UTC [3400901] STATEMENT:  UPDATE ft1 SET c2 = -c2 WHERE c1 = 1;
2023-07-26 04:49:09.136 UTC [3400901] ERROR:  new row violates check option for view "rw_view"
2023-07-26 04:49:09.136 UTC [3400901] DETAIL:  Failing row contains (10, 5).
2023-07-26 04:49:09.136 UTC [3400901] STATEMENT:  INSERT INTO rw_view VALUES (0, 5);
2023-07-26 04:49:09.149 UTC [3400901] ERROR:  new row violates check option for view "rw_view"
2023-07-26 04:49:09.149 UTC [3400901] DETAIL:  Failing row contains (20, 20).
2023-07-26 04:49:09.149 UTC [3400901] STATEMENT:  UPDATE rw_view SET b = b + 5;
2023-07-26 04:49:09.172 UTC [3400901] ERROR:  new row violates check option for view "rw_view"
2023-07-26 04:49:09.172 UTC [3400901] DETAIL:  Failing row contains (10, 5).
2023-07-26 04:49:09.172 UTC [3400901] STATEMENT:  INSERT INTO rw_view VALUES (0, 15), (0, 5);
2023-07-26 04:49:09.242 UTC [3400901] ERROR:  new row violates check option for view "rw_view"
2023-07-26 04:49:09.242 UTC [3400901] DETAIL:  Failing row contains (10, 5).
2023-07-26 04:49:09.242 UTC [3400901] STATEMENT:  INSERT INTO rw_view VALUES (0, 5);
2023-07-26 04:49:09.256 UTC [3400901] ERROR:  new row violates check option for view "rw_view"
2023-07-26 04:49:09.256 UTC [3400901] DETAIL:  Failing row contains (20, 20).
2023-07-26 04:49:09.256 UTC [3400901] STATEMENT:  UPDATE rw_view SET b = b + 5;
2023-07-26 04:49:09.285 UTC [3400901] ERROR:  new row violates check option for view "rw_view"
2023-07-26 04:49:09.285 UTC [3400901] DETAIL:  Failing row contains (10, 5).
2023-07-26 04:49:09.285 UTC [3400901] STATEMENT:  INSERT INTO rw_view VALUES (0, 15), (0, 5);
2023-07-26 04:49:09.380 UTC [3400925] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:09.380 UTC [3400925] STATEMENT:  INSERT INTO public.gloc1(a, b) VALUES ($1, DEFAULT)
2023-07-26 04:49:09.381 UTC [3400901] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:09.381 UTC [3400901] CONTEXT:  remote SQL command: INSERT INTO public.gloc1(a, b) VALUES ($1, DEFAULT)
2023-07-26 04:49:09.381 UTC [3400901] STATEMENT:  insert into grem1 (a) values (1), (2);
2023-07-26 04:49:09.391 UTC [3400925] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:09.391 UTC [3400925] STATEMENT:  INSERT INTO public.gloc1(a, b) VALUES ($1, DEFAULT)
2023-07-26 04:49:09.391 UTC [3400901] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:09.391 UTC [3400901] CONTEXT:  remote SQL command: INSERT INTO public.gloc1(a, b) VALUES ($1, DEFAULT)
	COPY grem1, line 1: "1"
2023-07-26 04:49:09.391 UTC [3400901] STATEMENT:  copy grem1 from stdin;
2023-07-26 04:49:09.411 UTC [3400926] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:09.411 UTC [3400926] STATEMENT:  INSERT INTO public.gloc1(a, b) VALUES ($1, DEFAULT), ($2, DEFAULT)
2023-07-26 04:49:09.411 UTC [3400901] ERROR:  cache lookup failed for type 23
2023-07-26 04:49:09.411 UTC [3400901] CONTEXT:  remote SQL command: INSERT INTO public.gloc1(a, b) VALUES ($1, DEFAULT), ($2, DEFAULT)
2023-07-26 04:49:09.411 UTC [3400901] STATEMENT:  insert into grem1 (a) values (1), (2);
2023-07-26 04:49:10.318 UTC [3400901] ERROR:  WHERE CURRENT OF is not supported for this table type
2023-07-26 04:49:10.318 UTC [3400901] STATEMENT:  update bar set f2 = null where current of c;
2023-07-26 04:49:10.612 UTC [3400901] ERROR:  cannot execute MERGE on relation "remp1"
2023-07-26 04:49:10.612 UTC [3400901] DETAIL:  This operation is not supported for foreign tables.
2023-07-26 04:49:10.612 UTC [3400901] STATEMENT:  merge into itrtest using (select 1, 'foo') as source on (true)
	  when matched then do nothing;
2023-07-26 04:49:10.631 UTC [3400901] ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
2023-07-26 04:49:10.631 UTC [3400901] STATEMENT:  insert into itrtest values (1, 'bar') on conflict (a) do nothing;
2023-07-26 04:49:10.631 UTC [3400901] ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
2023-07-26 04:49:10.631 UTC [3400901] STATEMENT:  insert into itrtest values (1, 'bar') on conflict (a) do update set b = excluded.b;
2023-07-26 04:49:10.773 UTC [3400927] ERROR:  new row for relation "loct" violates check constraint "loct_a_check"
2023-07-26 04:49:10.773 UTC [3400927] DETAIL:  Failing row contains (2, foo).
2023-07-26 04:49:10.773 UTC [3400927] STATEMENT:  UPDATE public.loct SET a = 2 WHERE ((b = 'foo')) RETURNING a, b
2023-07-26 04:49:10.773 UTC [3400901] ERROR:  new row for relation "loct" violates check constraint "loct_a_check"
2023-07-26 04:49:10.773 UTC [3400901] DETAIL:  Failing row contains (2, foo).
2023-07-26 04:49:10.773 UTC [3400901] CONTEXT:  remote SQL command: UPDATE public.loct SET a = 2 WHERE ((b = 'foo')) RETURNING a, b
2023-07-26 04:49:10.773 UTC [3400901] STATEMENT:  update utrtest set a = 2 where b = 'foo' returning *;
2023-07-26 04:49:10.775 UTC [3400901] ERROR:  cannot route tuples into foreign table to be updated "remp"
2023-07-26 04:49:10.775 UTC [3400901] STATEMENT:  update utrtest set a = 1 where b = 'qux' returning *;
2023-07-26 04:49:10.798 UTC [3400901] ERROR:  cannot route tuples into foreign table to be updated "remp"
2023-07-26 04:49:10.798 UTC [3400901] STATEMENT:  update utrtest set a = 1 where a = 1 or a = 2 returning *;
2023-07-26 04:49:10.828 UTC [3400901] ERROR:  cannot route tuples into foreign table to be updated "remp"
2023-07-26 04:49:10.828 UTC [3400901] STATEMENT:  update utrtest set a = 1 returning *;
2023-07-26 04:49:10.849 UTC [3400901] ERROR:  cannot route tuples into foreign table to be updated "remp"
2023-07-26 04:49:10.849 UTC [3400901] STATEMENT:  update utrtest set a = 1 from (values (1), (2)) s(x) where a = s.x returning *;
2023-07-26 04:49:10.896 UTC [3400901] ERROR:  cannot route tuples into foreign table to be updated "remp"
2023-07-26 04:49:10.896 UTC [3400901] STATEMENT:  update utrtest set a = 3 returning *;
2023-07-26 04:49:10.899 UTC [3400901] ERROR:  cannot route tuples into foreign table to be updated "remp"
2023-07-26 04:49:10.899 UTC [3400901] STATEMENT:  update utrtest set a = 3 from (values (2), (3)) s(x) where a = s.x returning *;
2023-07-26 04:49:11.059 UTC [3400927] ERROR:  new row for relation "loc2" violates check constraint "loc2_f1positive"
2023-07-26 04:49:11.059 UTC [3400927] DETAIL:  Failing row contains (-1, xyzzy).
2023-07-26 04:49:11.059 UTC [3400927] STATEMENT:  INSERT INTO public.loc2(f1, f2) VALUES ($1, $2)
2023-07-26 04:49:11.059 UTC [3400901] ERROR:  new row for relation "loc2" violates check constraint "loc2_f1positive"
2023-07-26 04:49:11.059 UTC [3400901] DETAIL:  Failing row contains (-1, xyzzy).
2023-07-26 04:49:11.059 UTC [3400901] CONTEXT:  remote SQL command: INSERT INTO public.loc2(f1, f2) VALUES ($1, $2)
	COPY rem2, line 1: "-1	xyzzy"
2023-07-26 04:49:11.059 UTC [3400901] STATEMENT:  copy rem2 from stdin;
2023-07-26 04:49:11.412 UTC [3400901] ERROR:  foreign table "tru_ftable" does not allow truncates
2023-07-26 04:49:11.412 UTC [3400901] STATEMENT:  TRUNCATE tru_ftable;
2023-07-26 04:49:11.439 UTC [3400901] ERROR:  foreign table "tru_ftable" does not allow truncates
2023-07-26 04:49:11.439 UTC [3400901] STATEMENT:  TRUNCATE tru_ftable;
2023-07-26 04:49:11.447 UTC [3400901] ERROR:  foreign table "tru_ftable" does not allow truncates
2023-07-26 04:49:11.447 UTC [3400901] STATEMENT:  TRUNCATE tru_ftable;
2023-07-26 04:49:11.511 UTC [3400929] ERROR:  cannot truncate a table referenced in a foreign key constraint
2023-07-26 04:49:11.511 UTC [3400929] DETAIL:  Table "tru_fk_table" references "tru_pk_table".
2023-07-26 04:49:11.511 UTC [3400929] HINT:  Truncate table "tru_fk_table" at the same time, or use TRUNCATE ... CASCADE.
2023-07-26 04:49:11.511 UTC [3400929] STATEMENT:  TRUNCATE public.tru_pk_table CONTINUE IDENTITY RESTRICT
2023-07-26 04:49:11.511 UTC [3400901] ERROR:  cannot truncate a table referenced in a foreign key constraint
2023-07-26 04:49:11.511 UTC [3400901] DETAIL:  Table "tru_fk_table" references "tru_pk_table".
2023-07-26 04:49:11.511 UTC [3400901] HINT:  Truncate table "tru_fk_table" at the same time, or use TRUNCATE ... CASCADE.
2023-07-26 04:49:11.511 UTC [3400901] CONTEXT:  remote SQL command: TRUNCATE public.tru_pk_table CONTINUE IDENTITY RESTRICT
2023-07-26 04:49:11.511 UTC [3400901] STATEMENT:  TRUNCATE tru_pk_ftable;
NOTICE:  truncate cascades to table "tru_fk_table"
NOTICE:  truncate cascades to table "tru_fk_table"
2023-07-26 04:49:11.825 UTC [3400901] ERROR:  cache lookup failed for type 18
2023-07-26 04:49:11.825 UTC [3400901] STATEMENT:  SELECT pol.polname, pol.polpermissive,
	  CASE WHEN pol.polroles = '{0}' THEN NULL ELSE pg_catalog.array_to_string(array(select rolname from pg_catalog.pg_roles where oid = any (pol.polroles) order by 1),',') END,
	  pg_catalog.pg_get_expr(pol.polqual, pol.polrelid),
	  pg_catalog.pg_get_expr(pol.polwithcheck, pol.polrelid),
	  CASE pol.polcmd
	    WHEN 'r' THEN 'SELECT'
	    WHEN 'a' THEN 'INSERT'
	    WHEN 'w' THEN 'UPDATE'
	    WHEN 'd' THEN 'DELETE'
	    END AS cmd
	FROM pg_catalog.pg_policy pol
	WHERE pol.polrelid = '16950' ORDER BY 1;
2023-07-26 04:49:11.852 UTC [3400901] ERROR:  cache lookup failed for type 18
2023-07-26 04:49:11.852 UTC [3400901] STATEMENT:  SELECT pol.polname, pol.polpermissive,
	  CASE WHEN pol.polroles = '{0}' THEN NULL ELSE pg_catalog.array_to_string(array(select rolname from pg_catalog.pg_roles where oid = any (pol.polroles) order by 1),',') END,
	  pg_catalog.pg_get_expr(pol.polqual, pol.polrelid),
	  pg_catalog.pg_get_expr(pol.polwithcheck, pol.polrelid),
	  CASE pol.polcmd
	    WHEN 'r' THEN 'SELECT'
	    WHEN 'a' THEN 'INSERT'
	    WHEN 'w' THEN 'UPDATE'
	    WHEN 'd' THEN 'DELETE'
	    END AS cmd
	FROM pg_catalog.pg_policy pol
	WHERE pol.polrelid = '16973' ORDER BY 1;
2023-07-26 04:49:11.874 UTC [3400901] ERROR:  cache lookup failed for type 18
2023-07-26 04:49:11.874 UTC [3400901] STATEMENT:  SELECT pol.polname, pol.polpermissive,
	  CASE WHEN pol.polroles = '{0}' THEN NULL ELSE pg_catalog.array_to_string(array(select rolname from pg_catalog.pg_roles where oid = any (pol.polroles) order by 1),',') END,
	  pg_catalog.pg_get_expr(pol.polqual, pol.polrelid),
	  pg_catalog.pg_get_expr(pol.polwithcheck, pol.polrelid),
	  CASE pol.polcmd
	    WHEN 'r' THEN 'SELECT'
	    WHEN 'a' THEN 'INSERT'
	    WHEN 'w' THEN 'UPDATE'
	    WHEN 'd' THEN 'DELETE'
	    END AS cmd
	FROM pg_catalog.pg_policy pol
	WHERE pol.polrelid = '16998' ORDER BY 1;
2023-07-26 04:49:11.895 UTC [3400901] ERROR:  relation "t1" already exists
2023-07-26 04:49:11.895 UTC [3400901] CONTEXT:  importing foreign table "t1"
2023-07-26 04:49:11.895 UTC [3400901] STATEMENT:  IMPORT FOREIGN SCHEMA import_source FROM SERVER loopback INTO import_dest4;
2023-07-26 04:49:11.895 UTC [3400901] ERROR:  schema "nonesuch" is not present on foreign server "loopback"
2023-07-26 04:49:11.895 UTC [3400901] STATEMENT:  IMPORT FOREIGN SCHEMA nonesuch FROM SERVER loopback INTO import_dest4;
2023-07-26 04:49:11.896 UTC [3400901] ERROR:  schema "notthere" does not exist
2023-07-26 04:49:11.896 UTC [3400901] STATEMENT:  IMPORT FOREIGN SCHEMA nonesuch FROM SERVER loopback INTO notthere;
2023-07-26 04:49:11.896 UTC [3400901] ERROR:  server "nowhere" does not exist
2023-07-26 04:49:11.896 UTC [3400901] STATEMENT:  IMPORT FOREIGN SCHEMA nonesuch FROM SERVER nowhere INTO notthere;
2023-07-26 04:49:11.919 UTC [3400901] ERROR:  type "public.Colors" does not exist at character 137
2023-07-26 04:49:11.919 UTC [3400901] QUERY:  CREATE FOREIGN TABLE t5 (
	  c1 integer OPTIONS (column_name 'c1'),
	  c2 text OPTIONS (column_name 'c2') COLLATE pg_catalog."C",
	  "Col" public."Colors" OPTIONS (column_name 'Col')
	) SERVER loopback
	OPTIONS (schema_name 'import_source', table_name 't5');
2023-07-26 04:49:11.919 UTC [3400901] CONTEXT:  importing foreign table "t5"
2023-07-26 04:49:11.919 UTC [3400901] STATEMENT:  IMPORT FOREIGN SCHEMA import_source LIMIT TO (t5)
	  FROM SERVER loopback INTO import_dest5;
2023-07-26 04:49:12.546 UTC [3400901] ERROR:  password is required
2023-07-26 04:49:12.546 UTC [3400901] DETAIL:  Non-superusers must provide a password in the user mapping.
2023-07-26 04:49:12.546 UTC [3400901] STATEMENT:  SELECT 1 FROM ft1_nopw LIMIT 1;
2023-07-26 04:49:12.546 UTC [3400901] ERROR:  invalid option "password"
2023-07-26 04:49:12.546 UTC [3400901] HINT:  Valid options in this context are: service, passfile, channel_binding, connect_timeout, dbname, host, hostaddr, port, options, application_name, keepalives, keepalives_idle, keepalives_interval, keepalives_count, tcp_user_timeout, sslmode, sslcompression, sslcert, sslkey, sslrootcert, sslcrl, sslcrldir, sslsni, requirepeer, ssl_min_protocol_version, ssl_max_protocol_version, gssencmode, krbsrvname, gsslib, target_session_attrs, use_remote_estimate, fdw_startup_cost, fdw_tuple_cost, extensions, updatable, truncatable, fetch_size, batch_size, async_capable, parallel_commit, keep_connections
2023-07-26 04:49:12.546 UTC [3400901] CONTEXT:  SQL statement "ALTER SERVER loopback_nopw OPTIONS (ADD password 'dummypw')"
	PL/pgSQL function inline_code_block line 3 at EXECUTE
2023-07-26 04:49:12.546 UTC [3400901] STATEMENT:  DO $d$
	    BEGIN
	        EXECUTE $$ALTER SERVER loopback_nopw OPTIONS (ADD password 'dummypw')$$;
	    END;
	$d$;
2023-07-26 04:49:12.561 UTC [3400901] ERROR:  password is required
2023-07-26 04:49:12.561 UTC [3400901] DETAIL:  Non-superuser cannot connect if the server does not request a password.
2023-07-26 04:49:12.561 UTC [3400901] HINT:  Target server's authentication method must be changed or password_required=false set in the user mapping attributes.
2023-07-26 04:49:12.561 UTC [3400901] STATEMENT:  SELECT 1 FROM ft1_nopw LIMIT 1;
2023-07-26 04:49:12.561 UTC [3400901] ERROR:  password_required=false is superuser-only
2023-07-26 04:49:12.561 UTC [3400901] HINT:  User mappings with the password_required option set to false may only be created or modified by the superuser.
2023-07-26 04:49:12.561 UTC [3400901] STATEMENT:  ALTER USER MAPPING FOR CURRENT_USER SERVER loopback_nopw OPTIONS (ADD password_required 'false');
2023-07-26 04:49:12.564 UTC [3400901] ERROR:  password is required
2023-07-26 04:49:12.564 UTC [3400901] DETAIL:  Non-superuser cannot connect if the server does not request a password.
2023-07-26 04:49:12.564 UTC [3400901] HINT:  Target server's authentication method must be changed or password_required=false set in the user mapping attributes.
2023-07-26 04:49:12.564 UTC [3400901] STATEMENT:  SELECT 1 FROM ft1_nopw LIMIT 1;
2023-07-26 04:49:12.582 UTC [3400901] ERROR:  sslcert and sslkey are superuser-only
2023-07-26 04:49:12.582 UTC [3400901] HINT:  User mappings with the sslcert or sslkey options set may only be created or modified by the superuser.
2023-07-26 04:49:12.582 UTC [3400901] STATEMENT:  ALTER USER MAPPING FOR CURRENT_USER SERVER loopback_nopw OPTIONS (ADD sslcert 'foo.crt');
2023-07-26 04:49:12.582 UTC [3400901] ERROR:  sslcert and sslkey are superuser-only
2023-07-26 04:49:12.582 UTC [3400901] HINT:  User mappings with the sslcert or sslkey options set may only be created or modified by the superuser.
2023-07-26 04:49:12.582 UTC [3400901] STATEMENT:  ALTER USER MAPPING FOR CURRENT_USER SERVER loopback_nopw OPTIONS (ADD sslkey 'foo.key');
2023-07-26 04:49:12.585 UTC [3400901] ERROR:  password is required
2023-07-26 04:49:12.585 UTC [3400901] DETAIL:  Non-superusers must provide a password in the user mapping.
2023-07-26 04:49:12.585 UTC [3400901] STATEMENT:  SELECT 1 FROM ft1_nopw LIMIT 1;
2023-07-26 04:49:12.622 UTC [3400901] ERROR:  cannot PREPARE a transaction that has operated on postgres_fdw foreign tables
2023-07-26 04:49:12.622 UTC [3400901] STATEMENT:  PREPARE TRANSACTION 'fdw_tpc';
2023-07-26 04:49:12.622 UTC [3400901] WARNING:  there is no transaction in progress
2023-07-26 04:49:12.643 UTC [3400936] FATAL:  terminating connection due to administrator command
2023-07-26 04:49:12.760 UTC [3400937] FATAL:  terminating connection due to administrator command
2023-07-26 04:49:12.862 UTC [3400901] ERROR:  FATAL:  terminating connection due to administrator command
	server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
2023-07-26 04:49:12.862 UTC [3400901] CONTEXT:  remote SQL command: SAVEPOINT s2
2023-07-26 04:49:12.862 UTC [3400901] STATEMENT:  SELECT 1 FROM ft1 LIMIT 1;
2023-07-26 04:49:12.918 UTC [3400901] WARNING:  cannot close connection for server "loopback" because it is still in use
2023-07-26 04:49:12.919 UTC [3400901] WARNING:  cannot close connection for server "loopback" because it is still in use
2023-07-26 04:49:12.919 UTC [3400901] WARNING:  cannot close connection for server "loopback2" because it is still in use
2023-07-26 04:49:12.920 UTC [3400901] ERROR:  server "unknownserver" does not exist
2023-07-26 04:49:12.920 UTC [3400901] STATEMENT:  SELECT postgres_fdw_disconnect('unknownserver');
2023-07-26 04:49:13.407 UTC [3400901] ERROR:  cannot route tuples into foreign table to be updated "batch_cp_upd_test1_f"
2023-07-26 04:49:13.407 UTC [3400901] STATEMENT:  UPDATE batch_cp_upd_test t SET a = 1 FROM (VALUES (1), (2)) s(a) WHERE t.a = s.a;
2023-07-26 04:49:14.716 UTC [3400901] ERROR:  invalid value for floating point option "fdw_startup_cost": 100$%$#$#
2023-07-26 04:49:14.716 UTC [3400901] STATEMENT:  CREATE SERVER inv_scst FOREIGN DATA WRAPPER postgres_fdw
		OPTIONS(fdw_startup_cost '100$%$#$#');
2023-07-26 04:49:14.716 UTC [3400901] ERROR:  invalid value for floating point option "fdw_tuple_cost": 100$%$#$#
2023-07-26 04:49:14.716 UTC [3400901] STATEMENT:  CREATE SERVER inv_scst FOREIGN DATA WRAPPER postgres_fdw
		OPTIONS(fdw_tuple_cost '100$%$#$#');
2023-07-26 04:49:14.718 UTC [3400901] ERROR:  invalid value for integer option "fetch_size": 100$%$#$#
2023-07-26 04:49:14.718 UTC [3400901] STATEMENT:  CREATE FOREIGN TABLE inv_fsz (c1 int )
		SERVER loopback OPTIONS (fetch_size '100$%$#$#');
2023-07-26 04:49:14.719 UTC [3400901] ERROR:  invalid value for integer option "batch_size": 100$%$#$#
2023-07-26 04:49:14.719 UTC [3400901] STATEMENT:  CREATE FOREIGN TABLE inv_bsz (c1 int )
		SERVER loopback OPTIONS (batch_size '100$%$#$#');
2023-07-26 04:49:14.719 UTC [3400901] ERROR:  invalid option "nonexistent"
2023-07-26 04:49:14.719 UTC [3400901] HINT:  There are no valid options in this context.
2023-07-26 04:49:14.719 UTC [3400901] STATEMENT:  ALTER FOREIGN DATA WRAPPER postgres_fdw OPTIONS (nonexistent 'fdw');
