2023-07-26 07:51:51.373 UTC [1016520] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-26 07:51:51.374 UTC [1016520] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-26 07:51:51.384 UTC [1016520] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-26 07:51:51.400 UTC [1016523] LOG:  database system was shut down at 2023-07-26 07:51:51 UTC
2023-07-26 07:51:51.412 UTC [1016520] LOG:  database system is ready to accept connections
2023-07-26 07:51:51.419 UTC [1016526] LOG:  pg_cron scheduler started
2023-07-26 07:51:52.090 UTC [1016548] ERROR:  could not create unique index "idx_badindex_n"
2023-07-26 07:51:52.090 UTC [1016548] DETAIL:  Key (n)=(10) is duplicated.
2023-07-26 07:51:52.090 UTC [1016548] STATEMENT:  CREATE UNIQUE INDEX CONCURRENTLY idx_badindex_n ON tbl_badindex (n);
2023-07-26 07:51:58.951 UTC [1016721] ERROR:  permission denied for schema repack at character 8
2023-07-26 07:51:58.951 UTC [1016721] STATEMENT:  select repack.version(), repack.version_sql()
2023-07-26 07:52:01.714 UTC [1016810] ERROR:  table name not found for OID 1
2023-07-26 07:52:01.714 UTC [1016810] STATEMENT:  SELECT repack.get_order_by('issue321_idx'::regclass::oid, 1);
2023-07-26 07:52:01.714 UTC [1016810] ERROR:  cache lookup failed for index 1
2023-07-26 07:52:01.714 UTC [1016810] STATEMENT:  SELECT repack.get_order_by(1, 1);
