2023-07-27 03:09:04.629 UTC [2222251] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-27 03:09:04.630 UTC [2222251] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-27 03:09:04.636 UTC [2222251] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-27 03:09:04.645 UTC [2222254] LOG:  database system was shut down at 2023-07-27 03:09:04 UTC
2023-07-27 03:09:04.651 UTC [2222251] LOG:  database system is ready to accept connections
2023-07-27 03:09:04.846 UTC [2222279] ERROR:  ltree syntax error at character 1
2023-07-27 03:09:04.846 UTC [2222279] CONTEXT:  while creating return value
	PL/Python function "test2"
2023-07-27 03:09:04.846 UTC [2222279] STATEMENT:  SELECT test2();
2023-07-27 03:09:04.857 UTC [2222252] LOG:  checkpoint starting: immediate force wait
2023-07-27 03:09:04.885 UTC [2222252] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.005 s, total=0.028 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4473 kB, estimate=4473 kB
2023-07-27 03:09:05.045 UTC [2222309] ERROR:  not a Python mapping
2023-07-27 03:09:05.045 UTC [2222309] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-27 03:09:05.045 UTC [2222309] STATEMENT:  SELECT test1bad();
2023-07-27 03:09:05.054 UTC [2222309] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-27 03:09:05.054 UTC [2222309] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-27 03:09:05.054 UTC [2222309] STATEMENT:  SELECT test2dom('bar');
