2023-07-27 00:05:04.326 UTC [2196959] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-27 00:05:04.326 UTC [2196959] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-27 00:05:04.341 UTC [2196959] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-27 00:05:04.358 UTC [2196962] LOG:  database system was shut down at 2023-07-27 00:05:04 UTC
2023-07-27 00:05:04.369 UTC [2196959] LOG:  database system is ready to accept connections
2023-07-27 00:05:04.643 UTC [2196984] ERROR:  not a Python mapping
2023-07-27 00:05:04.643 UTC [2196984] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-27 00:05:04.643 UTC [2196984] STATEMENT:  SELECT test1bad();
2023-07-27 00:05:04.671 UTC [2196984] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-27 00:05:04.671 UTC [2196984] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-27 00:05:04.671 UTC [2196984] STATEMENT:  SELECT test2dom('bar');
